version: '3.6'
services:
  midsa-rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management-alpine
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    volumes:
      - type: bind
        source: ./rabbitmq/rabbitmq.config
        target: /etc/rabbitmq/rabbitmq.config
      - type: bind
        source: ./rabbitmq/rabbitmq-defs.json
        target: /etc/rabbitmq/rabbitmq-defs.json
      - type: bind
        source: ./rabbitmq/enabled_plugins
        target: /etc/rabbitmq/enabled_plugins